### ISSUE TITLE
"error: no such column" on complex "conflict target"

### ISSUE THREAD

**Issue by ewildgoose** [elixir-sqlite/exqlite#169] opened 2021-10-19 14:29 UTC
Hi, running this the following in the console is accepted:
```
INSERT INTO "counter_interfaces" ("device_id","device_type") VALUES ("123","3g") ON CONFLICT ("device_id", COALESCE("sim_id", "")) DO UPDATE SET "device_id" = EXCLUDED."device_id","device_type" = EXCLUDED."device_type","sim_id" = EXCLUDED."sim_id";
```

However, when run through exqlite I get an error:
```
iex(7)> {:ok, statement} = Exqlite.Sqlite3.prepare(conn, ~s<INSERT INTO "counter_interfaces" ("device_id","device_type") VALUES (?,?) ON CONFLICT ("device_id",coalesce("sim_id", "")) DO UPDATE SET "device_id" = EXCLUDED."device_id","device_type" = EXCLUDED."device_type","sim_id" = EXCLUDED."sim_id">)                               ** 

(MatchError) no match of right hand side value: {:error, "no such column: "}
```

The database definition is as follows:
```
    create table("counter_interfaces") do
      add :device_id,   :string, null: false
      add :device_type, :string,  null: false
      add :sim_id,      :string, null: true
    end
    create unique_index("counter_interfaces", [:device_id, "coalesce(sim_id, '')"], name: :unique_counter_interfaces_on_any_sim_id)
```

What I'm trying to achieve is a situation where I have a unique constraint on multiple device_id/sim_id pairs, including the case that sim_id is nil (the default case for sqlite is that uniqueness is not enforced for columns which are null)

I'm not clear if this problem is coming from the sqlite parser or something in exqlite? That it works ok on the sqlite command line suggests exqlite? Any suggestions?

**Comment by warmwaffles** [comment] 2021-10-19 21:15
@ewildgoose https://github.com/elixir-sqlite/ecto_sqlite3/pull/59 that PR is a fix for this ya?

**Comment by warmwaffles** [comment] 2021-10-20 13:52
Exqlite is just a driver library. It doesn't do the SQL generation. That is done by `ecto_sqlite` so we need to resolve the issue there. I'll check that PR out later this evening and do some poking.

**Comment by ewildgoose** [comment] 2021-10-20 14:48
Hi, I think I'm explaining myself badly. I generate a bunch of SQL "by hand". This SQL functions when run directly in the sqlite cli. However, near identical SQL returns an error when passed into Exqlite.Sqlite3.prepare(conn, "hand generated SQL")

The ecto_sqlite change simply allows me to get to the point of finding myself blocked here. However, checking your library code suggests that "Exqlite.Sqlite3.prepare" is a pretty thin wrapper around the C api, and so that implies the problem is deeper in sqlite I think?

So my question is something like: Why this SQL is accepted in the sqlite cli, but not accepted through the "Exqlite.Sqlite3.prepare" call?

**Comment by warmwaffles** [comment] 2021-10-20 15:17
That's a good question. I didn't fully read the part about running it in the `prepare` part. 

Can you copy paste the sql schema for the table? So I can poke around in iex.

**Comment by ewildgoose** [comment] 2022-08-04 14:37
Ooh! Interesting! Nice spot!

**Comment by greg-rychlewski** [comment] 2023-12-13 12:54
It seems like double quoted strings were disabled on purpose: https://github.com/elixir-sqlite/exqlite/commit/88b431698b52395304db2192007952a3ac881766

So I believe everything is working as intended

**Comment by ruslandoga** [comment] 2024-10-14 04:24
I think this issue can be closed.

**Closed** 2024-10-14 12:52 UTC
Labels: bug
