### ISSUE TITLE
Could not compile dependency :exqlite

### ISSUE THREAD

**Issue by aukuste** [elixir-sqlite/exqlite#272] opened 2023-12-18 20:43 UTC
I seem to have an issue with getting exqlite compiled.

I updated my dependencies recently for a project, where one of them is ecto_sqlite3.

When trying to compile the project, the compilation fails when trying to compile exqlite:

```
==> exqlite
Downloading precompiled NIF to /home/user/.cache/exqlite-nif-2.17-x86_64-linux-gnu-0.17.0.tar.gz
could not compile dependency :exqlite, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile exqlite --force", update it with "mix deps.update exqlite" or clean it with "mix deps.clean exqlite"
** (ArgumentError) unknown application: :certifi
    (elixir 1.15.7) lib/application.ex:1010: Application.app_dir/1
    (elixir 1.15.7) lib/application.ex:1037: Application.app_dir/2
    (elixir_make 0.7.7) lib/elixir_make/artefact.ex:267: ElixirMake.Artefact.cacerts_options/0
    (elixir_make 0.7.7) lib/elixir_make/artefact.ex:244: ElixirMake.Artefact.download/1
    (elixir_make 0.7.7) lib/mix/tasks/compile.elixir_make.ex:222: Mix.Tasks.Compile.ElixirMake.download_or_reuse_nif/3
    (elixir_make 0.7.7) lib/mix/tasks/compile.elixir_make.ex:160: Mix.Tasks.Compile.ElixirMake.run/1
    (mix 1.15.7) lib/mix/task.ex:455: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.7) lib/mix/tasks/compile.all.ex:124: Mix.Tasks.Compile.All.run_compiler/2
```

Exqlite is version 0.17.0.

Some system info:
I'm running Fedora Linux 38
Erlang version: Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]
Elixir version: Elixir 1.15.7 (compiled with Erlang/OTP 26)

Any ideas on why this is happening?

**Comment by warmwaffles** [comment] 2023-12-18 20:48
Odd https://hex.pm/packages/certifi

**Comment by aukuste** [comment] 2023-12-19 10:09
It seems like it's the download of exqlite-nif-2.17-x86_64-linux-gnu-0.17.0.tar.gz that just fails immediately. If I manually download that file from the github releases and place it in ~/.cache, exqlite compiles without any issues.

**Comment by warmwaffles** [comment] 2023-12-19 16:50
@cocoa-xu I'm not well versed in the precompile logic, do you think you can lend a hand here?

**Comment by cocoa-xu** [comment] 2023-12-19 17:04
@aukuste That's kinda strange... and I cannot reproduce it in my Linux machine (which runs Ubuntu 20.04). Maybe I'll try to find a Fedora machine and try it tomorrow. And could you please let me know the exact version of Erlang installed on your computer? I was using 26.0.2 in my setup.

```bash
$ erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), halt().' -noshell
26.0.2
```

**Comment by aukuste** [comment] 2023-12-19 18:00
@cocoa-xu 26.2.1

**Comment by aukuste** [comment] 2023-12-19 18:22
If I create a new project and add ecto_sqlite3 and ecto_sql to it, it works without problem, but if I then remove `~/.cache/exqlite-nif-2.17-x86_64-linux-gnu-0.17.0.tar.gz` and add `{:timex, "~> 3.7"}` to the deps in mix.exs, run `mix deps.get`, and the `mix compile`, then I can reproduce the problem consistently.

**Comment by ollien** [comment] 2024-01-16 01:05
I'm seeing this exact same failure signature using the official [`elixir:1.16.0`](https://hub.docker.com/layers/library/elixir/1.16.0/images/sha256-329afc52225c14b1b4979ad42c85088708316e3d3e6598b1cc1d79e6d249aef9?context=explore docker image).

**Comment by josevalim** [comment] 2024-01-17 12:48
Fixed in elixir_make. Thanks @cocoa-xu for the report and initial fix.

**Closed** 2024-01-17 16:02 UTC
